### ISSUE TITLE
Maven Central Has Wrong Artifacts

### ISSUE THREAD

**Issue by ptahchiev** [JavaMoney/jsr354-ri#186]
Version 1.2 of moneta that was promoted to Maven central has wrong artifact names:

http://repo1.maven.org/maven2/org/javamoney/moneta/1.2/

In this folder we see `moneta-convert`, `moneta-core`, `moneta-ecb` and `moneta-imf` but maven is expecting to find jar/pom with the artifactId (`moneta`).

**Comment by keilw** [comment]
None of them show on MavenCentral yet: https://search.maven.org/#search%7Cga%7C1%7Cmoneta
only shows the versions as far as 2 years ago. @atsticks Are you in the process of deploying the RI(s) there, too?

**Comment by ark1** [comment]
Is there work-around solutions for this or do we have to wait a correction to be made?

**Comment by keilw** [comment]
Afraid there is no workaround at the moment.

**Comment by atsticks** [comment]
I am currently fixing this, keeping fingers crossed.

**Comment by atsticks** [comment]
Sync result:

**Comment by keilw** [comment]
Is there a reason why the RI won't build and cannot find the API module?

**Comment by atsticks** [comment]
fixed. Also available now on maven central.

**Comment by keilw** [comment]
@atsticks Maybe subject to another issue, I think I opened one already, but why is https://travis-ci.org/JavaMoney/jsr354-ri still failing?

**Comment by keilw** [comment]
Had to reopen this, because when fixing https://github.com/JavaMoney/jsr354-ri/issues/187 I saw, the MavenCentral artifact also has the wrong 1.0.2-SNAPSHOT API version in the POM, so the build will likely fail also for downstream artifacts. Either 1.2 can be replaced or maybe it should be called 1.2.1 then (a FIX of 1.2 not a new version)

**Comment by keilw** [comment]
@ptahchiev @atsticks Anything still missing here or can we also close that after 1.2.1?

**Comment by whiskeysierra** [comment]
`org.javamoney:moneta` only exists in type `pom`. Using it as a dependency requires:

```xml
<dependency>
    <groupId>org.javamoney</groupId>
    <artifactId>moneta</artifactId>
    <version>1.2</version>
    <type>pom</type>
</dependency>
```

But from what I can tell the artifacts were compiled using with target 1.9 and are therefore unusable within java8 environments.

**Comment by whiskeysierra** [comment]
> has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by keilw** [comment]
That's why there is [1.2.1](https://search.maven.org/#artifactdetails%7Corg.javamoney%7Cmoneta%7C1.2.1%7Cpom)

**Comment by whiskeysierra** [comment]
True, it's not necessary. But it's easier for your clients that are using both the java8+ and java7 version depending on the jdk version.

**Comment by keilw** [comment]
I leave it to @atsticks if he thinks it's worth the effort of deploying.

**Comment by keilw** [comment]
While there is another issue https://github.com/JavaMoney/jsr354-ri/issues/194 I think we can close this one now.
